### ISSUE TITLE
More errors after Update to 0.4.1

### ISSUE THREAD

**Issue by TbsJah** [UncleSamSwiss/ioBroker.luxtronik2#165]
![image](https://user-images.githubusercontent.com/34193151/147874901-4ee45ab8-ba14-42a8-b5c8-9c2eca7bf960.png)
After updating to version 0.4.1 I get more error messages

**Comment by TbsJah** [comment]
The problem seems to be solved with the latest update from Coolchip
Could you please update the dependencies

https://github.com/coolchip/luxtronik2/issues/28

**Comment by UncleSamSwiss** [comment]
@TbsJah I just released adapter version 0.4.2, please let me know if this fixes the issues you are seeing.

**Comment by TbsJah** [comment]
![image](https://user-images.githubusercontent.com/34193151/151402362-026f471f-e8c6-4aa0-ac1c-90899a3c2ba7.png)
Unfortunately, this does not fix the polling errors

**Comment by coolchip** [comment]
This is a little bit hard for me to debug but it seems that the luxtronik try to send data after timeout or invalid data. When did that error happend? Once a day or more often? What you have to do to bring it back to life? Restart ioBroker or did it recover alone?
